"""
Email sender module for the AI News Agent.
"""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from pathlib import Path
from config import Config


class EmailSender:
    """Handle sending emails with PDF attachments via Gmail."""
    
    def __init__(self):
        """Initialize the email sender with Gmail configuration."""
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.sender_email = Config.GMAIL_USER
        self.sender_password = Config.GMAIL_PASSWORD
    
    def send_report(self, pdf_path: str, recipient_email: str = None) -> bool:
        """
        Send the PDF report via email.
        
        Args:
            pdf_path (str): Path to the PDF file to send.
            recipient_email (str): Email address of the recipient.
            
        Returns:
            bool: True if email was sent successfully, False otherwise.
        """
        if not recipient_email:
            recipient_email = Config.RECIPIENT_EMAIL
        
        try:
            # Create message
            message = self._create_message(pdf_path, recipient_email)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(message)
            
            print(f"✅ Email sent successfully to {recipient_email}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send email: {str(e)}")
            return False
    
    def _create_message(self, pdf_path: str, recipient_email: str) -> MIMEMultipart:
        """
        Create the email message with PDF attachment.
        
        Args:
            pdf_path (str): Path to the PDF file.
            recipient_email (str): Recipient email address.
            
        Returns:
            MIMEMultipart: The complete email message.
        """
        # Create message container
        message = MIMEMultipart()
        message['From'] = self.sender_email
        message['To'] = recipient_email
        message['Subject'] = f"Daily AI News Report - {datetime.now().strftime('%B %d, %Y')}"
        
        # Email body
        body = self._create_email_body()
        message.attach(MIMEText(body, 'html'))
        
        # Attach PDF
        self._attach_pdf(message, pdf_path)
        
        return message
    
    def _create_email_body(self) -> str:
        """
        Create the HTML body of the email.
        
        Returns:
            str: HTML content for the email body.
        """
        current_date = datetime.now().strftime('%B %d, %Y')
        
        html = f"""
        <html>
            <head></head>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                    <h2 style="color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px;">
                        🤖 Daily AI & Automation News Report
                    </h2>
                    <p>Hello,</p>
                    <p>
                        Please find attached your daily AI and automation news report for 
                        <strong>{current_date}</strong>.
                    </p>
                    <p>
                        This report contains the latest news, trends, and developments in the fields of 
                        artificial intelligence and automation technology, compiled by our AI research agent.
                    </p>
                    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
                    <p style="font-size: 12px; color: #666;">
                        This is an automated email generated by the AI News Agent.<br>
                        Powered by LangChain and Gemini 1.5 Flash.
                    </p>
                </div>
            </body>
        </html>
        """
        
        return html
    
    def _attach_pdf(self, message: MIMEMultipart, pdf_path: str):
        """
        Attach the PDF file to the email message.
        
        Args:
            message (MIMEMultipart): The email message object.
            pdf_path (str): Path to the PDF file.
        """
        pdf_filename = Path(pdf_path).name
        
        # Open PDF file in binary mode
        with open(pdf_path, 'rb') as attachment:
            # Create MIMEBase object
            part = MIMEBase('application', 'pdf')
            part.set_payload(attachment.read())
        
        # Encode to base64
        encoders.encode_base64(part)
        
        # Add header
        part.add_header(
            'Content-Disposition',
            f'attachment; filename= {pdf_filename}',
        )
        
        # Attach to message
        message.attach(part)
