id: daily-ai-news-report
namespace: company.team

description: |
  Daily AI and Automation News Report Agent
  Executes Monday-Friday at 7:00 AM to research AI news, generate PDF report, and send via email

labels:
  project: ai-news-agent
  category: automation

tasks:
  - id: working-directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Guilherme-Silva-Lopes/ai-news-agent-
        branch: main

      - id: install-dependencies
        type: io.kestra.plugin.scripts.python.Commands
        description: Install requirements for all tasks
        containerImage: python:3.11-slim
        commands:
          - pip install --no-cache-dir -r requirements.txt

      - id: research-news
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 1 - Research News
        containerImage: python:3.11-slim
        commands:
          - python agent.py --output news_content.txt
        env:
          GOOGLE_API_KEY: "{{ kv('GOOGLE_API_KEY') }}"
          TAVILY_API_KEY: "{{ kv('TAVILY_API_KEY') }}"
          RECEIVER_EMAIL: "{{ kv('RECEIVER_EMAIL') }}"
          # Dummy values for config validation (only needed for Email phase)
          GMAIL_CLIENT_ID: "dummy"
          GMAIL_CLIENT_SECRET: "dummy"
          GMAIL_REFRESH_TOKEN: "dummy"

      - id: generate-pdf
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 2 - Generate PDF
        containerImage: python:3.11-slim
        commands:
          - python pdf_generator.py --input news_content.txt --output ai_news_report.pdf
        outputFiles:
          - ai_news_report.pdf

      - id: send-email
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 3 - Send Email
        containerImage: python:3.11-slim
        commands:
          - python email_sender.py --file ai_news_report.pdf
        env:
          GOOGLE_API_KEY: "{{ kv('GOOGLE_API_KEY') }}"
          TAVILY_API_KEY: "{{ kv('TAVILY_API_KEY') }}"
          RECEIVER_EMAIL: "{{ kv('RECEIVER_EMAIL') }}"
          GMAIL_CLIENT_ID: "{{ kv('GMAIL_CREDENTIALS').client_id }}"
          GMAIL_CLIENT_SECRET: "{{ kv('GMAIL_CREDENTIALS').client_secret }}"
          GMAIL_REFRESH_TOKEN: "{{ kv('GMAIL_CREDENTIALS').refresh_token }}"

errors:
  - id: error-handler
    type: io.kestra.plugin.core.log.Log
    description: Handle execution errors
    message: "❌ Error in Daily AI News Report workflow: {{ error.message }}"

triggers:
  - id: daily-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    description: Run Monday to Friday at 7:00 AM
    cron: "0 7 * * 1-5"
    timezone: America/Sao_Paulo
    lateMaximumDelay: PT1H
