id: daily-ai-news-report
namespace: company.team

description: |
  Daily AI and Automation News Report Agent
  Executes Monday-Friday at 7:00 AM to research AI news, generate PDF report, and send via email

labels:
  project: ai-news-agent
  category: automation

tasks:
  - id: working-directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Guilherme-Silva-Lopes/ai-news-agent-
        branch: main

      - id: research-news
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 1 - Research News
        containerImage: python:3.11-slim
        commands:
          - pip install --no-cache-dir -r requirements.txt
          - python agent.py --output news_content.txt
        env:
          GOOGLE_API_KEY: "{{ kv('GOOGLE_API_KEY') }}"
          TAVILY_API_KEY: "{{ kv('TAVILY_API_KEY') }}"

      - id: generate-pdf
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 2 - Generate PDF
        containerImage: python:3.11-slim
        commands:
          - pip install --no-cache-dir -r requirements.txt
          - python pdf_generator.py --input news_content.txt --output ai_news_report.pdf
        outputFiles:
          - ai_news_report.pdf

      - id: send-email
        type: io.kestra.plugin.notifications.mail.MailSend
        description: Phase 3 - Send Email with PDF Report
        from: "{{ kv('GMAIL_CREDENTIALS').user }}"
        to: 
          - "{{ kv('GMAIL_CREDENTIALS').recipient }}"
        subject: "🤖 Daily AI News Report - {{ now() | date('yyyy-MM-dd') }}"
        htmlTextContent: |
          <html>
          <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <h2 style="color: #2563eb;">🤖 Daily AI & Automation News Report</h2>
            <p>Hello!</p>
            <p>Your daily AI and automation news report is ready. Please find the comprehensive PDF report attached.</p>
            <p style="margin-top: 20px;">
              <strong>Report Date:</strong> {{ now() | date('MMMM dd, yyyy') }}<br>
              <strong>Generated by:</strong> AI News Agent powered by Gemini
            </p>
            <hr style="border: 1px solid #e5e7eb; margin: 20px 0;">
            <p style="font-size: 12px; color: #6b7280;">
              This report was automatically generated by Kestra workflow.<br>
              Execution ID: {{ execution.id }}
            </p>
          </body>
          </html>
        attachments:
          - name: "AI_News_Report_{{ now() | date('yyyy-MM-dd') }}.pdf"
            uri: "{{ outputs['generate-pdf'].outputFiles['ai_news_report.pdf'] }}"
        host: smtp.gmail.com
        port: 587
        username: "{{ kv('GMAIL_CREDENTIALS').user }}"
        password: "{{ kv('GMAIL_CREDENTIALS').password }}"

errors:
  - id: error-handler
    type: io.kestra.plugin.core.log.Log
    description: Handle execution errors
    message: "❌ Error in workflow execution. Execution ID: {{ execution.id }}"

triggers:
  - id: daily-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    description: Run Monday to Friday at 7:00 AM
    cron: "0 7 * * 1-5"
    timezone: America/Sao_Paulo
    lateMaximumDelay: PT1H
