id: daily-ai-news-report
namespace: company.team

description: |
  Daily AI and Automation News Report Agent
  Executes Monday-Friday at 7:00 AM to research AI news, generate PDF report, and send via email

labels:
  project: ai-news-agent
  category: automation

tasks:
  - id: working-directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Guilherme-Silva-Lopes/ai-news-agent-
        branch: main

      - id: research-news
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 1 - Research News
        containerImage: python:3.11-slim
        commands:
          - pip install --no-cache-dir -r requirements.txt
          - python agent.py --output news_content.txt
        env:
          GOOGLE_API_KEY: "{{ kv('GOOGLE_API_KEY') }}"
          TAVILY_API_KEY: "{{ kv('TAVILY_API_KEY') }}"
          RECEIVER_EMAIL: "{{ kv('RECEIVER_EMAIL') }}"
          GMAIL_CLIENT_ID: "dummy"
          GMAIL_CLIENT_SECRET: "dummy"
          GMAIL_REFRESH_TOKEN: "dummy"

      - id: generate-pdf
        type: io.kestra.plugin.scripts.python.Commands
        description: Phase 2 - Generate PDF
        containerImage: python:3.11-slim
        commands:
          - pip install --no-cache-dir -r requirements.txt
          - python pdf_generator.py --input news_content.txt --output ai_news_report.pdf
        outputFiles:
          - ai_news_report.pdf

      - id: send-email
        type: io.kestra.plugin.notifications.mail.MailSend
        description: Phase 3 - Send Email via Native Kestra Plugin
        from: "{{ kv('GMAIL_EMAIL') }}"
        to: 
          - "{{ kv('RECEIVER_EMAIL') }}"
        subject: "Daily AI & Automation News Report - {{ now() | date('MMMM dd, yyyy') }}"
        htmlTextContent: |
          <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
              <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2 style="color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px;">
                  🤖 Daily AI & Automation News Report
                </h2>
                <p>Attached is your daily AI and automation news report for <strong>{{ now() | date('MMMM dd, yyyy') }}</strong>.</p>
                <p>This report was automatically generated by your AI News Agent running on Kestra.</p>
                <p style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e5e5; color: #666; font-size: 12px;">
                  Powered by LangChain, Google Gemini, and Tavily Search
                </p>
              </div>
            </body>
          </html>
        attachments:
          - "{{ outputs['generate-pdf'].outputFiles['ai_news_report.pdf'] }}"
        host: smtp.gmail.com
        port: 587
        username: "{{ kv('GMAIL_EMAIL') }}"
        password: "{{ kv('GMAIL_APP_PASSWORD') }}"
        transportStrategy: SMTP_TLS

errors:
  - id: error-handler
    type: io.kestra.plugin.core.log.Log
    description: Handle execution errors
    message: "❌ Error in workflow execution. Execution ID: {{ execution.id }}"

triggers:
  - id: daily-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    description: Run Monday to Friday at 7:00 AM
    cron: "0 7 * * 1-5"
    timezone: America/Sao_Paulo
    lateMaximumDelay: PT1H
