"""
PDF Report Generator for AI News Agent.
"""
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.colors import HexColor
from config import Config


class NewsReportGenerator:
    """Generate professional PDF reports from news content."""
    
    def __init__(self, filename=None):
        """
        Initialize the PDF generator.
        
        Args:
            filename (str): Output filename for the PDF report.
        """
        self.filename = filename or Config.REPORT_FILENAME
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Set up custom styles for the PDF."""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=HexColor('#666666'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        # News heading style
        self.styles.add(ParagraphStyle(
            name='NewsHeading',
            parent=self.styles['Heading3'],
            fontSize=14,
            textColor=HexColor('#2563eb'),
            spaceAfter=10,
            fontName='Helvetica-Bold'
        ))
        
        # Body text style
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            textColor=HexColor('#1a1a1a'),
            alignment=TA_JUSTIFY,
            spaceAfter=12,
            fontName='Helvetica'
        ))
    
    def generate_report(self, content: str, output_path: str = None) -> str:
        """
        Generate a PDF report from the news content.
        
        Args:
            content (str): The news content generated by the agent.
            output_path (str): Optional custom output path.
            
        Returns:
            str: Path to the generated PDF file.
        """
        if output_path:
            self.filename = output_path
        
        # Create the PDF document
        doc = SimpleDocTemplate(
            self.filename,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )
        
        # Container for the 'Flowable' objects
        story = []
        
        # Add title
        title = Paragraph(Config.REPORT_TITLE, self.styles['CustomTitle'])
        story.append(title)
        
        # Add date
        current_date = datetime.now().strftime("%B %d, %Y")
        subtitle = Paragraph(current_date, self.styles['CustomSubtitle'])
        story.append(subtitle)
        story.append(Spacer(1, 0.3 * inch))
        
        # Process and add content
        self._add_content_to_story(story, content)
        
        # Build the PDF
        doc.build(story)
        
        return self.filename
    
    def _clean_text(self, text: str) -> str:
        """
        Clean text by removing excessive quotes and formatting artifacts.
        
        Args:
            text (str): Text to clean.
            
        Returns:
            str: Cleaned text.
        """
        import re
        
        # Remove excessive double quotes around phrases
        # But keep quotes that are part of actual quotes
        text = re.sub(r'""([^"]+)""', r'\1', text)  # Remove double-double quotes
        text = re.sub(r'"([A-Z][^"]{10,})"', r'\1', text)  # Remove quotes around capitalized phrases
        
        return text
    
    def _make_urls_clickable(self, text: str) -> str:
        """
        Convert URLs in text to clickable HTML links.
        
        Args:
            text (str): Text containing URLs.
            
        Returns:
            str: Text with clickable links.
        """
        import re
        import html
        
        # First escape HTML to prevent XML errors
        text = html.escape(text)
        
        # Pattern to match URLs
        url_pattern = r'(https?://[^\s<>"]+)'
        
        # Replace URLs with clickable links
        text = re.sub(url_pattern, r'<link href="\1" color="blue"><u>\1</u></link>', text)
        
        return text
    
    def _add_content_to_story(self, story, content: str):
        """
        Process the content and add it to the PDF story.
        
        Args:
            story (list): List of flowable objects for the PDF.
            content (str): The content to add.
        """
        # Clean the entire content first
        content = self._clean_text(content)
        
        # Split content into paragraphs
        paragraphs = content.split('\n\n')
        
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue
            
            # Make URLs clickable (this also escapes HTML)
            para_processed = self._make_urls_clickable(para)
            
            # Check if it's a heading (starts with # or is all caps and short)
            if para.startswith('#'):
                # Remove markdown heading symbols
                heading_text = para.lstrip('#').strip()
                heading_processed = self._make_urls_clickable(heading_text)
                p = Paragraph(f"<b>{heading_processed}</b>", self.styles['NewsHeading'])
                story.append(p)
            elif para.startswith('**') and para.endswith('**'):
                # Bold text as heading
                heading_text = para.strip('*').strip()
                heading_processed = self._make_urls_clickable(heading_text)
                p = Paragraph(f"<b>{heading_processed}</b>", self.styles['NewsHeading'])
                story.append(p)
            elif len(para) < 100 and para.isupper():
                # All caps short text as heading
                p = Paragraph(para_processed, self.styles['NewsHeading'])
                story.append(p)
            else:
                # Regular paragraph with clickable URLs
                p = Paragraph(para_processed, self.styles['CustomBody'])
                story.append(p)
            
            story.append(Spacer(1, 0.1 * inch))

if __name__ == "__main__":
    import argparse
    import sys
    from pathlib import Path
    
    parser = argparse.ArgumentParser(description="AI News Agent - PDF Generation")
    parser.add_argument("--input", required=True, help="Path to the input text file with news content")
    parser.add_argument("--output", help="Path to save the generated PDF")
    args = parser.parse_args()
    
    try:
        # Read content
        input_path = Path(args.input)
        if not input_path.exists():
            raise FileNotFoundError(f"Input file not found: {input_path}")
            
        content = input_path.read_text(encoding='utf-8')
        
        # Generate PDF
        generator = NewsReportGenerator(filename=args.output)
        pdf_path = generator.generate_report(content, args.output)
        
        print(f"✅ PDF generated successfully: {pdf_path}")
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        sys.exit(1)
